# Default values for generic-three-tier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
frontend:

  secrets:
    simpleMountPath: /etc/frontend-secret
    advancedMounts: []
    #- mountPath: /etc/nginx/nginx.key
    #  subPath: nginx.key
    data: []
    #- name: nginx.key
    #  content: secret data here

  config:
    simpleMountPath: /etc/frontend
    advancedMounts: []
    #- mountPath: /etc/nginx/nginx.conf
    #  subPath: nginx.conf
    data: []
    #- name: nginx.conf
    #  content: non secret frontend data here

  replicas: 1

  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    # enabled: false
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  env: []
  volumes: []
  volumeMounts: []

  livenessProbe: {}
  readinessProbe: {}

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

backend:

  secrets:
    simpleMountPath: /etc/backend-secret
    advancedMounts: []
    #- mountPath: /etc/nginx/nginx.key
    #  subPath: nginx.key
    data: []
    #- name: nginx.key
    #  content: secret data here

  config:
    simpleMountPath: /etc/backend
    advancedMounts: []
    #- mountPath: /etc/nginx/nginx.conf
    #  subPath: nginx.conf
    data: []
    #- name: nginx.conf
    #  content: non secret backend data here

  replicas: 1

  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    # enabled: false
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    path: /backend
    hosts:
      - chart-example.local
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  env: []
  volumes: []
  volumeMounts: []

  livenessProbe: {}
  readinessProbe: {}

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

db:
  bitnamiEtcd: false
